version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: smartlocksystem_db
      POSTGRES_MAX_CONNECTIONS: 1000
      POSTGRES_USER: smartlocksystem
      POSTGRES_PASSWORD: smartlocksystem
    ports:
      - "6543:5432"
    working_dir: /var/lib/postgresql/data
    volumes:
      - Postgres:/var/lib/postgresql/data
    tty: true
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./MqttBroker/config:/mosquitto/config
      - ./MqttBroker/data:/mosquitto/data
      - ./MqttBroker/log:/mosquitto/log
volumes:
  Postgres: